CREATE TABLE weekend (
    uuid VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36),
    lundi BOOLEAN DEFAULT FALSE,
    mardi BOOLEAN DEFAULT FALSE,
    mercredi BOOLEAN DEFAULT FALSE,
    jeudi BOOLEAN DEFAULT FALSE,
    vendredi BOOLEAN DEFAULT FALSE,
    samedi BOOLEAN DEFAULT FALSE,
    dimanche BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)